# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Concatenate files
        # You may pin to the exact commit or the version.
        # uses: ftnext/action-concatenate-files@0f9d7d7aa5d0372c628ee949f24fffa0ddb5344e
        uses: ftnext/action-concatenate-files@v1.0.1
        with:
          # A string which represents paths of concatenated files.
          sources: Python.gitignore Node.gitignore
          # Path to the created file.
          destination: Meta.txt
